"""empty message

Revision ID: d60e22e5d48d
Revises: 6af9b56f6629
Create Date: 2022-05-21 17:29:45.110499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60e22e5d48d'
down_revision = '6af9b56f6629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_genres_artist_id_fkey', 'artist_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artist_genres', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'venues', ['venue_id'], ['id'])
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artists', ['artist_id'], ['id'])
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    op.create_foreign_key('artist_genres_artist_id_fkey', 'artist_genres', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
